### ISSUE TITLE
I can't watch the video because it's private (vimeo)

### ISSUE THREAD

**Issue by jaredsurya** [learn-co-curriculum/phase-3-lecture-videos-hashes#1]
### Canvas Link

https://learning.flatironschool.com/courses/5286/pages/video-hashes?module_item_id=376623

### Concern

It's just a private video that I can't view. 

### Suggested Changes

make the video public

**Comment by lizbur10** [comment]
Hi @jaredsurya ! There is currently a problem with the Venmo account. It should be cleared up soon. Apologies for the inconvenience 💙
