### ISSUE TITLE
Video does not load

### ISSUE THREAD

**Issue by Kalunodragon** [learn-co-curriculum/phase-3-lecture-videos-hashes#2]
### Canvas Link

https://learning.flatironschool.com/courses/5835/pages/video-hashes?module_item_id=485468

### Concern

Video that loaded yesterday seems to no longer load when page is opened. Tired restarting computer after trying to restart the browser and to no avail. Link from Dev Tools also doesn't seem to work

**Comment by lizbur10** [comment]
Hi @Kalunodragon ! Thanks for reporting this issue. The video appears to be working now. It was probably a temporary issue with the Vimeo server.

Thanks for contributing to the Flatiron School curriculum 💙
